### ISSUE TITLE
Equities Page

### ISSUE THREAD

**Issue by mengyewgau** [mengyewgau/Smartfolio#6]
Cc:

Hi all
  
### Pain

This issue is a part of #2 , which is Smartfolio Stage 1

### Tasks

- [ ] On Load
- [ ] Individual Asset View Navigation
- [ ] Add asset to watchlist
- [ ] Navigate to watchlist

### Screenshots

![image](https://github.com/mengyewgau/Smartfolio/assets/61722401/3cd5cf34-cc57-41d3-ba2c-fae9e76b3b50)

Thanks!
