### ISSUE TITLE
Individual Stock Page

### ISSUE THREAD

**Issue by mengyewgau** [mengyewgau/Smartfolio#8]
Cc:

Hi 
  
### Pain

This issue is a part of Smartfolio Stage 1 #2 

### Tasks

- [ ] On load page
- [ ] Add stock to portfolio for verified users only
- [ ] Add stock to watchlist  for verified users only

### Acceptance Criteria

Everyone can view a stock, but only registered users can add it to their watchlist and portfolio. Any attempts create a redirect
### Screenshots

![image](https://github.com/mengyewgau/Smartfolio/assets/61722401/8123e0bd-9e2e-45ac-86c1-8d138fe4c3e8)
![image](https://github.com/mengyewgau/Smartfolio/assets/61722401/a3deb032-cd24-4298-ac54-90bfe36f8134)

Thanks!
